services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    depends_on:
      - matterserver
    ports:
      - "8123:8123"
    volumes:
      - ./DockerVolumes/homeassistant:/config
    environment:
      - TZ=Europe/Paris

  matterserver:
    container_name: matterserver
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    ports:
      - "5580:5580"
      - "5540:5540/udp"
    volumes:
      - ./DockerVolumes/matterserver:/data
    environment:
      - TZ=Europe/Paris

  reflector:
    container_name: reflector
    image: luligu/reflector-client:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Paris
