services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    depends_on:
      - matterserver
    ports:
      - "8123:8123"
    volumes:
      - ./DockerVolumes/homeassistant:/config
    environment:
      - TZ=Europe/Paris

  matterserver:
    container_name: matterserver
    image: ghcr.io/home-assistant-libs/python-matter-server:stable
    restart: unless-stopped
    ports:
      - "5580:5580"
      - "5540:5540/udp"
    volumes:
      - ./DockerVolumes/matterserver:/data
    environment:
      - TZ=Europe/Paris

  mb_mdns:
    container_name: mb_mdns
    image: luligu/matterbridge:latest
    restart: unless-stopped
    command: [ "mb_mdns", "--no-timeout" ]
    environment:
      - TZ=Europe/Paris

  mb_reflector:
    container_name: mb_reflector
    image: luligu/matterbridge:latest
    restart: unless-stopped
    command: [ "mb_mdns", "--reflector-client" ]
    environment:
      - TZ=Europe/Paris
